export const COMPLETE_TODO ="COMPLETE_TODO";
export const ADD_TODO ="ADD_TODO";
export const REMOVE_TODO ="REMOVE_TODO";
export const UPDATE_TODO ="UPDATE_TODO";
export const NESTEDADD_TODO ="NESTEDADD_TODO";
export const NESTEDREMOVE_TODO ="NESTEDREMOVE_TODO";
export const NESTEDUPDATE_TODO ="NESTEDUPDATE_TODO";
